// <auto-generated />
using System;
using CMS.ComplaintService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.ComplaintService.Migrations
{
    [DbContext(typeof(ComplaintDbContext))]
    [Migration("20251125140114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("CMS.ComplaintService.Domain.Entities.Complaint", b =>
                {
                    b.Property<Guid>("ComplaintID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsumerID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupportPersonID")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ComplaintID");

                    b.HasIndex("TenantID", "Status");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("CMS.ComplaintService.Domain.Entities.ComplaintAuditHistory", b =>
                {
                    b.Property<Guid>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComplaintID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditID");

                    b.HasIndex("ComplaintID");

                    b.ToTable("ComplaintAuditHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
